controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.50
  min_vel_x: 0.05
  max_rotational_vel: 2.5
  min_in_place_rotational_vel: 1.0
  acc_lim_th: 3.2
  acc_lim_x: 2.50
  acc_lim_y: 2.50

  holonomic_robot: false
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 5.0
  heading_lookahead: 0.4
  oscillation_reset_dist: 0.25

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

